### ISSUE TITLE
ブログのデザインがデフォルトすぎるのでいい感じにする

### ISSUE THREAD

**Issue by moto-sbt** [moto-sbt/nextjs-blog#23]

**Comment by moto-sbt** [comment]
案1
![image](https://user-images.githubusercontent.com/74887303/182382128-ad6673d2-3c73-483f-8449-d3bb5998735b.png)


`global.css`に以下追加

```css
body {

    ...

    color: gainsboro;
    background: linear-gradient(220.55deg, #220e43 0%, #272726 50%);
}

.github_icon_link {
    color: gainsboro;

    ...
}
```
